// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: spots/proto/filters_response.proto

package dto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on FilterGetAllResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *FilterGetAllResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Status

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FilterGetAllResponseValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// FilterGetAllResponseValidationError is the validation error returned by
// FilterGetAllResponse.Validate if the designated constraints aren't met.
type FilterGetAllResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FilterGetAllResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FilterGetAllResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FilterGetAllResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FilterGetAllResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FilterGetAllResponseValidationError) ErrorName() string {
	return "FilterGetAllResponseValidationError"
}

// Error satisfies the builtin error interface
func (e FilterGetAllResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFilterGetAllResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FilterGetAllResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FilterGetAllResponseValidationError{}

// Validate checks the field values on FilterData with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *FilterData) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Type

	for idx, item := range m.GetValues() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FilterDataValidationError{
					field:  fmt.Sprintf("Values[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// FilterDataValidationError is the validation error returned by
// FilterData.Validate if the designated constraints aren't met.
type FilterDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FilterDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FilterDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FilterDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FilterDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FilterDataValidationError) ErrorName() string { return "FilterDataValidationError" }

// Error satisfies the builtin error interface
func (e FilterDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFilterData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FilterDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FilterDataValidationError{}

// Validate checks the field values on FilterValueData with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *FilterValueData) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Name

	return nil
}

// FilterValueDataValidationError is the validation error returned by
// FilterValueData.Validate if the designated constraints aren't met.
type FilterValueDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FilterValueDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FilterValueDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FilterValueDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FilterValueDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FilterValueDataValidationError) ErrorName() string { return "FilterValueDataValidationError" }

// Error satisfies the builtin error interface
func (e FilterValueDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFilterValueData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FilterValueDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FilterValueDataValidationError{}
