// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: spots/proto/filters_response.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterGetAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   []*FilterData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *FilterGetAllResponse) Reset() {
	*x = FilterGetAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spots_proto_filters_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterGetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterGetAllResponse) ProtoMessage() {}

func (x *FilterGetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spots_proto_filters_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterGetAllResponse.ProtoReflect.Descriptor instead.
func (*FilterGetAllResponse) Descriptor() ([]byte, []int) {
	return file_spots_proto_filters_response_proto_rawDescGZIP(), []int{0}
}

func (x *FilterGetAllResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FilterGetAllResponse) GetData() []*FilterData {
	if x != nil {
		return x.Data
	}
	return nil
}

type FilterData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type   string             `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Values []*FilterValueData `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *FilterData) Reset() {
	*x = FilterData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spots_proto_filters_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterData) ProtoMessage() {}

func (x *FilterData) ProtoReflect() protoreflect.Message {
	mi := &file_spots_proto_filters_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterData.ProtoReflect.Descriptor instead.
func (*FilterData) Descriptor() ([]byte, []int) {
	return file_spots_proto_filters_response_proto_rawDescGZIP(), []int{1}
}

func (x *FilterData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FilterData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FilterData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FilterData) GetValues() []*FilterValueData {
	if x != nil {
		return x.Values
	}
	return nil
}

type FilterValueData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FilterValueData) Reset() {
	*x = FilterValueData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spots_proto_filters_response_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterValueData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterValueData) ProtoMessage() {}

func (x *FilterValueData) ProtoReflect() protoreflect.Message {
	mi := &file_spots_proto_filters_response_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterValueData.ProtoReflect.Descriptor instead.
func (*FilterValueData) Descriptor() ([]byte, []int) {
	return file_spots_proto_filters_response_proto_rawDescGZIP(), []int{2}
}

func (x *FilterValueData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FilterValueData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_spots_proto_filters_response_proto protoreflect.FileDescriptor

var file_spots_proto_filters_response_proto_rawDesc = []byte{
	0x0a, 0x22, 0x73, 0x70, 0x6f, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x54, 0x0a, 0x14, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x73, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x35, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x2f, 0x64, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spots_proto_filters_response_proto_rawDescOnce sync.Once
	file_spots_proto_filters_response_proto_rawDescData = file_spots_proto_filters_response_proto_rawDesc
)

func file_spots_proto_filters_response_proto_rawDescGZIP() []byte {
	file_spots_proto_filters_response_proto_rawDescOnce.Do(func() {
		file_spots_proto_filters_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_spots_proto_filters_response_proto_rawDescData)
	})
	return file_spots_proto_filters_response_proto_rawDescData
}

var file_spots_proto_filters_response_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spots_proto_filters_response_proto_goTypes = []interface{}{
	(*FilterGetAllResponse)(nil), // 0: main.FilterGetAllResponse
	(*FilterData)(nil),           // 1: main.FilterData
	(*FilterValueData)(nil),      // 2: main.FilterValueData
}
var file_spots_proto_filters_response_proto_depIdxs = []int32{
	1, // 0: main.FilterGetAllResponse.data:type_name -> main.FilterData
	2, // 1: main.FilterData.values:type_name -> main.FilterValueData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spots_proto_filters_response_proto_init() }
func file_spots_proto_filters_response_proto_init() {
	if File_spots_proto_filters_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spots_proto_filters_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterGetAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spots_proto_filters_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spots_proto_filters_response_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterValueData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spots_proto_filters_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spots_proto_filters_response_proto_goTypes,
		DependencyIndexes: file_spots_proto_filters_response_proto_depIdxs,
		MessageInfos:      file_spots_proto_filters_response_proto_msgTypes,
	}.Build()
	File_spots_proto_filters_response_proto = out.File
	file_spots_proto_filters_response_proto_rawDesc = nil
	file_spots_proto_filters_response_proto_goTypes = nil
	file_spots_proto_filters_response_proto_depIdxs = nil
}
