// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/spots_request.proto

package dto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SpotsAddRequest struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string              `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Coordinates          *RequestCoordinates `protobuf:"bytes,3,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Lighting             bool                `protobuf:"varint,4,opt,name=lighting,proto3" json:"lighting,omitempty"`
	Friendly             bool                `protobuf:"varint,5,opt,name=friendly,proto3" json:"friendly,omitempty"`
	Verified             bool                `protobuf:"varint,6,opt,name=verified,proto3" json:"verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SpotsAddRequest) Reset()         { *m = SpotsAddRequest{} }
func (m *SpotsAddRequest) String() string { return proto.CompactTextString(m) }
func (*SpotsAddRequest) ProtoMessage()    {}
func (*SpotsAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1ba4769525620c8, []int{0}
}

func (m *SpotsAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotsAddRequest.Unmarshal(m, b)
}
func (m *SpotsAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotsAddRequest.Marshal(b, m, deterministic)
}
func (m *SpotsAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotsAddRequest.Merge(m, src)
}
func (m *SpotsAddRequest) XXX_Size() int {
	return xxx_messageInfo_SpotsAddRequest.Size(m)
}
func (m *SpotsAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotsAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SpotsAddRequest proto.InternalMessageInfo

func (m *SpotsAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SpotsAddRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SpotsAddRequest) GetCoordinates() *RequestCoordinates {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *SpotsAddRequest) GetLighting() bool {
	if m != nil {
		return m.Lighting
	}
	return false
}

func (m *SpotsAddRequest) GetFriendly() bool {
	if m != nil {
		return m.Friendly
	}
	return false
}

func (m *SpotsAddRequest) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

type SpotsUpdateRequest struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string              `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Coordinates          *RequestCoordinates `protobuf:"bytes,3,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Lighting             bool                `protobuf:"varint,4,opt,name=lighting,proto3" json:"lighting,omitempty"`
	Friendly             bool                `protobuf:"varint,5,opt,name=friendly,proto3" json:"friendly,omitempty"`
	Verified             bool                `protobuf:"varint,6,opt,name=verified,proto3" json:"verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SpotsUpdateRequest) Reset()         { *m = SpotsUpdateRequest{} }
func (m *SpotsUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*SpotsUpdateRequest) ProtoMessage()    {}
func (*SpotsUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1ba4769525620c8, []int{1}
}

func (m *SpotsUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotsUpdateRequest.Unmarshal(m, b)
}
func (m *SpotsUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotsUpdateRequest.Marshal(b, m, deterministic)
}
func (m *SpotsUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotsUpdateRequest.Merge(m, src)
}
func (m *SpotsUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_SpotsUpdateRequest.Size(m)
}
func (m *SpotsUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotsUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SpotsUpdateRequest proto.InternalMessageInfo

func (m *SpotsUpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SpotsUpdateRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SpotsUpdateRequest) GetCoordinates() *RequestCoordinates {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *SpotsUpdateRequest) GetLighting() bool {
	if m != nil {
		return m.Lighting
	}
	return false
}

func (m *SpotsUpdateRequest) GetFriendly() bool {
	if m != nil {
		return m.Friendly
	}
	return false
}

func (m *SpotsUpdateRequest) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

type RequestCoordinates struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Long                 float64  `protobuf:"fixed64,2,opt,name=long,proto3" json:"long,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestCoordinates) Reset()         { *m = RequestCoordinates{} }
func (m *RequestCoordinates) String() string { return proto.CompactTextString(m) }
func (*RequestCoordinates) ProtoMessage()    {}
func (*RequestCoordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1ba4769525620c8, []int{2}
}

func (m *RequestCoordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestCoordinates.Unmarshal(m, b)
}
func (m *RequestCoordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestCoordinates.Marshal(b, m, deterministic)
}
func (m *RequestCoordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestCoordinates.Merge(m, src)
}
func (m *RequestCoordinates) XXX_Size() int {
	return xxx_messageInfo_RequestCoordinates.Size(m)
}
func (m *RequestCoordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestCoordinates.DiscardUnknown(m)
}

var xxx_messageInfo_RequestCoordinates proto.InternalMessageInfo

func (m *RequestCoordinates) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *RequestCoordinates) GetLong() float64 {
	if m != nil {
		return m.Long
	}
	return 0
}

func init() {
	proto.RegisterType((*SpotsAddRequest)(nil), "main.SpotsAddRequest")
	proto.RegisterType((*SpotsUpdateRequest)(nil), "main.SpotsUpdateRequest")
	proto.RegisterType((*RequestCoordinates)(nil), "main.RequestCoordinates")
}

func init() {
	proto.RegisterFile("proto/spots_request.proto", fileDescriptor_b1ba4769525620c8)
}

var fileDescriptor_b1ba4769525620c8 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x91, 0xbf, 0x4a, 0x04, 0x31,
	0x10, 0xc6, 0x89, 0xb7, 0xf7, 0xc7, 0xb9, 0x42, 0x99, 0x2a, 0x5a, 0x2d, 0x57, 0x6d, 0xb5, 0x07,
	0xda, 0x5d, 0xa7, 0xbe, 0x41, 0xc4, 0xc6, 0x46, 0xa2, 0x33, 0xb7, 0x06, 0xb2, 0xc9, 0x9a, 0x44,
	0xc1, 0xa7, 0x14, 0x7c, 0x22, 0x49, 0xd6, 0x55, 0xc1, 0x37, 0xb8, 0xee, 0xfb, 0xe6, 0x17, 0x26,
	0xfc, 0x18, 0x38, 0x1b, 0x82, 0x4f, 0x7e, 0x1b, 0x07, 0x9f, 0xe2, 0x43, 0xe0, 0x97, 0x57, 0x8e,
	0xa9, 0x2d, 0x33, 0xac, 0x7a, 0x6d, 0xdc, 0xe6, 0x43, 0xc0, 0xc9, 0x6d, 0xa6, 0x57, 0x44, 0x6a,
	0xe4, 0x88, 0x50, 0x39, 0xdd, 0xb3, 0x14, 0xb5, 0x68, 0x8e, 0x55, 0xc9, 0x28, 0x61, 0xa9, 0x89,
	0x02, 0xc7, 0x28, 0x8f, 0xca, 0x78, 0xaa, 0xb8, 0x83, 0xf5, 0x93, 0xf7, 0x81, 0x8c, 0xd3, 0x89,
	0xa3, 0x9c, 0xd5, 0xa2, 0x59, 0x5f, 0xc8, 0x36, 0x6f, 0x6f, 0xbf, 0x37, 0xde, 0xfc, 0x72, 0xf5,
	0xf7, 0x31, 0x9e, 0xc3, 0xca, 0x9a, 0xee, 0x39, 0x19, 0xd7, 0xc9, 0xaa, 0x16, 0xcd, 0x4a, 0xfd,
	0xf4, 0xcc, 0xf6, 0xc1, 0xb0, 0x23, 0xfb, 0x2e, 0xe7, 0x23, 0x9b, 0x7a, 0x66, 0x6f, 0x1c, 0xcc,
	0xde, 0x30, 0xc9, 0xc5, 0xc8, 0xa6, 0xbe, 0xf9, 0x14, 0x80, 0xc5, 0xe8, 0x6e, 0x20, 0x9d, 0xf8,
	0x30, 0xa4, 0x76, 0x80, 0xff, 0xbf, 0xc5, 0x53, 0x98, 0x59, 0x9d, 0x8a, 0x92, 0x50, 0x39, 0x66,
	0x4b, 0xeb, 0x5d, 0x57, 0x74, 0x84, 0x2a, 0xf9, 0x7a, 0x79, 0x3f, 0x6f, 0xb7, 0x94, 0xfc, 0xe3,
	0xa2, 0x1c, 0xfe, 0xf2, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x15, 0x7b, 0x22, 0x15, 0x02, 0x00,
	0x00,
}
