// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/spots_response.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpotsAddData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SpotsAddData) Reset() {
	*x = SpotsAddData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spots_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpotsAddData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotsAddData) ProtoMessage() {}

func (x *SpotsAddData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spots_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotsAddData.ProtoReflect.Descriptor instead.
func (*SpotsAddData) Descriptor() ([]byte, []int) {
	return file_proto_spots_response_proto_rawDescGZIP(), []int{0}
}

func (x *SpotsAddData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SpotsAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   *SpotsAddData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SpotsAddResponse) Reset() {
	*x = SpotsAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spots_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpotsAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotsAddResponse) ProtoMessage() {}

func (x *SpotsAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spots_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotsAddResponse.ProtoReflect.Descriptor instead.
func (*SpotsAddResponse) Descriptor() ([]byte, []int) {
	return file_proto_spots_response_proto_rawDescGZIP(), []int{1}
}

func (x *SpotsAddResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SpotsAddResponse) GetData() *SpotsAddData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_spots_response_proto protoreflect.FileDescriptor

var file_proto_spots_response_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x6f, 0x74, 0x73, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61,
	0x69, 0x6e, 0x22, 0x1e, 0x0a, 0x0c, 0x53, 0x70, 0x6f, 0x74, 0x73, 0x41, 0x64, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x52, 0x0a, 0x10, 0x53, 0x70, 0x6f, 0x74, 0x73, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x26,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x53, 0x70, 0x6f, 0x74, 0x73, 0x41, 0x64, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x64, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_spots_response_proto_rawDescOnce sync.Once
	file_proto_spots_response_proto_rawDescData = file_proto_spots_response_proto_rawDesc
)

func file_proto_spots_response_proto_rawDescGZIP() []byte {
	file_proto_spots_response_proto_rawDescOnce.Do(func() {
		file_proto_spots_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_spots_response_proto_rawDescData)
	})
	return file_proto_spots_response_proto_rawDescData
}

var file_proto_spots_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_spots_response_proto_goTypes = []interface{}{
	(*SpotsAddData)(nil),     // 0: main.SpotsAddData
	(*SpotsAddResponse)(nil), // 1: main.SpotsAddResponse
}
var file_proto_spots_response_proto_depIdxs = []int32{
	0, // 0: main.SpotsAddResponse.data:type_name -> main.SpotsAddData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_spots_response_proto_init() }
func file_proto_spots_response_proto_init() {
	if File_proto_spots_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_spots_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpotsAddData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spots_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpotsAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_spots_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_spots_response_proto_goTypes,
		DependencyIndexes: file_proto_spots_response_proto_depIdxs,
		MessageInfos:      file_proto_spots_response_proto_msgTypes,
	}.Build()
	File_proto_spots_response_proto = out.File
	file_proto_spots_response_proto_rawDesc = nil
	file_proto_spots_response_proto_goTypes = nil
	file_proto_spots_response_proto_depIdxs = nil
}
