// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: spots/proto/spots_response.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpotsAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   *SpotsAddData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SpotsAddResponse) Reset() {
	*x = SpotsAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spots_proto_spots_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpotsAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotsAddResponse) ProtoMessage() {}

func (x *SpotsAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spots_proto_spots_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotsAddResponse.ProtoReflect.Descriptor instead.
func (*SpotsAddResponse) Descriptor() ([]byte, []int) {
	return file_spots_proto_spots_response_proto_rawDescGZIP(), []int{0}
}

func (x *SpotsAddResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SpotsAddResponse) GetData() *SpotsAddData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SpotsAddData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SpotsAddData) Reset() {
	*x = SpotsAddData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spots_proto_spots_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpotsAddData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotsAddData) ProtoMessage() {}

func (x *SpotsAddData) ProtoReflect() protoreflect.Message {
	mi := &file_spots_proto_spots_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotsAddData.ProtoReflect.Descriptor instead.
func (*SpotsAddData) Descriptor() ([]byte, []int) {
	return file_spots_proto_spots_response_proto_rawDescGZIP(), []int{1}
}

func (x *SpotsAddData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SpotsUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   *SpotsUpdateData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SpotsUpdateResponse) Reset() {
	*x = SpotsUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spots_proto_spots_response_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpotsUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotsUpdateResponse) ProtoMessage() {}

func (x *SpotsUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spots_proto_spots_response_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotsUpdateResponse.ProtoReflect.Descriptor instead.
func (*SpotsUpdateResponse) Descriptor() ([]byte, []int) {
	return file_spots_proto_spots_response_proto_rawDescGZIP(), []int{2}
}

func (x *SpotsUpdateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SpotsUpdateResponse) GetData() *SpotsUpdateData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SpotsUpdateData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address     string               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Coordinates *ResponseCoordinates `protobuf:"bytes,4,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Lighting    bool                 `protobuf:"varint,5,opt,name=lighting,proto3" json:"lighting,omitempty"`
	Friendly    bool                 `protobuf:"varint,6,opt,name=friendly,proto3" json:"friendly,omitempty"`
	Verified    bool                 `protobuf:"varint,7,opt,name=verified,proto3" json:"verified,omitempty"`
}

func (x *SpotsUpdateData) Reset() {
	*x = SpotsUpdateData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spots_proto_spots_response_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpotsUpdateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotsUpdateData) ProtoMessage() {}

func (x *SpotsUpdateData) ProtoReflect() protoreflect.Message {
	mi := &file_spots_proto_spots_response_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotsUpdateData.ProtoReflect.Descriptor instead.
func (*SpotsUpdateData) Descriptor() ([]byte, []int) {
	return file_spots_proto_spots_response_proto_rawDescGZIP(), []int{3}
}

func (x *SpotsUpdateData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpotsUpdateData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpotsUpdateData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SpotsUpdateData) GetCoordinates() *ResponseCoordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *SpotsUpdateData) GetLighting() bool {
	if x != nil {
		return x.Lighting
	}
	return false
}

func (x *SpotsUpdateData) GetFriendly() bool {
	if x != nil {
		return x.Friendly
	}
	return false
}

func (x *SpotsUpdateData) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type ResponseCoordinates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat  float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Long float64 `protobuf:"fixed64,2,opt,name=long,proto3" json:"long,omitempty"`
}

func (x *ResponseCoordinates) Reset() {
	*x = ResponseCoordinates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spots_proto_spots_response_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCoordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCoordinates) ProtoMessage() {}

func (x *ResponseCoordinates) ProtoReflect() protoreflect.Message {
	mi := &file_spots_proto_spots_response_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCoordinates.ProtoReflect.Descriptor instead.
func (*ResponseCoordinates) Descriptor() ([]byte, []int) {
	return file_spots_proto_spots_response_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseCoordinates) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *ResponseCoordinates) GetLong() float64 {
	if x != nil {
		return x.Long
	}
	return 0
}

type SpotsGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   *SpotsGetData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SpotsGetResponse) Reset() {
	*x = SpotsGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spots_proto_spots_response_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpotsGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotsGetResponse) ProtoMessage() {}

func (x *SpotsGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spots_proto_spots_response_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotsGetResponse.ProtoReflect.Descriptor instead.
func (*SpotsGetResponse) Descriptor() ([]byte, []int) {
	return file_spots_proto_spots_response_proto_rawDescGZIP(), []int{5}
}

func (x *SpotsGetResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SpotsGetResponse) GetData() *SpotsGetData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SpotsGetData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address     string               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Coordinates *ResponseCoordinates `protobuf:"bytes,4,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Lighting    bool                 `protobuf:"varint,5,opt,name=lighting,proto3" json:"lighting,omitempty"`
	Friendly    bool                 `protobuf:"varint,6,opt,name=friendly,proto3" json:"friendly,omitempty"`
	Verified    bool                 `protobuf:"varint,7,opt,name=verified,proto3" json:"verified,omitempty"`
}

func (x *SpotsGetData) Reset() {
	*x = SpotsGetData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spots_proto_spots_response_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpotsGetData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotsGetData) ProtoMessage() {}

func (x *SpotsGetData) ProtoReflect() protoreflect.Message {
	mi := &file_spots_proto_spots_response_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotsGetData.ProtoReflect.Descriptor instead.
func (*SpotsGetData) Descriptor() ([]byte, []int) {
	return file_spots_proto_spots_response_proto_rawDescGZIP(), []int{6}
}

func (x *SpotsGetData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpotsGetData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpotsGetData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SpotsGetData) GetCoordinates() *ResponseCoordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *SpotsGetData) GetLighting() bool {
	if x != nil {
		return x.Lighting
	}
	return false
}

func (x *SpotsGetData) GetFriendly() bool {
	if x != nil {
		return x.Friendly
	}
	return false
}

func (x *SpotsGetData) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type SpotsGetAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   []*SpotsGetData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *SpotsGetAllResponse) Reset() {
	*x = SpotsGetAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spots_proto_spots_response_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpotsGetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotsGetAllResponse) ProtoMessage() {}

func (x *SpotsGetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spots_proto_spots_response_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotsGetAllResponse.ProtoReflect.Descriptor instead.
func (*SpotsGetAllResponse) Descriptor() ([]byte, []int) {
	return file_spots_proto_spots_response_proto_rawDescGZIP(), []int{7}
}

func (x *SpotsGetAllResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SpotsGetAllResponse) GetData() []*SpotsGetData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_spots_proto_spots_response_proto protoreflect.FileDescriptor

var file_spots_proto_spots_response_proto_rawDesc = []byte{
	0x0a, 0x20, 0x73, 0x70, 0x6f, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70,
	0x6f, 0x74, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x52, 0x0a, 0x10, 0x53, 0x70, 0x6f, 0x74,
	0x73, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x70, 0x6f, 0x74, 0x73, 0x41,
	0x64, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1e, 0x0a, 0x0c,
	0x53, 0x70, 0x6f, 0x74, 0x73, 0x41, 0x64, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x58, 0x0a, 0x13,
	0x53, 0x70, 0x6f, 0x74, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x29, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x53, 0x70, 0x6f, 0x74, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xe0, 0x01, 0x0a, 0x0f, 0x53, 0x70, 0x6f, 0x74, 0x73,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x6f,
	0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x69, 0x6e,
	0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x69, 0x6e,
	0x67, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x6c, 0x79, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x6c, 0x79, 0x12, 0x1a, 0x0a,
	0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x22, 0x3b, 0x0a, 0x13, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c,
	0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x22, 0x52, 0x0a, 0x10, 0x53, 0x70, 0x6f, 0x74, 0x73, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x70, 0x6f, 0x74, 0x73, 0x47, 0x65, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xdd, 0x01, 0x0a, 0x0c, 0x53,
	0x70, 0x6f, 0x74, 0x73, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x6f, 0x6f,
	0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f,
	0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x69,
	0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x69,
	0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x6c, 0x79, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x6c, 0x79, 0x12, 0x1a,
	0x0a, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x22, 0x55, 0x0a, 0x13, 0x53, 0x70,
	0x6f, 0x74, 0x73, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53,
	0x70, 0x6f, 0x74, 0x73, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x64, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_spots_proto_spots_response_proto_rawDescOnce sync.Once
	file_spots_proto_spots_response_proto_rawDescData = file_spots_proto_spots_response_proto_rawDesc
)

func file_spots_proto_spots_response_proto_rawDescGZIP() []byte {
	file_spots_proto_spots_response_proto_rawDescOnce.Do(func() {
		file_spots_proto_spots_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_spots_proto_spots_response_proto_rawDescData)
	})
	return file_spots_proto_spots_response_proto_rawDescData
}

var file_spots_proto_spots_response_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_spots_proto_spots_response_proto_goTypes = []interface{}{
	(*SpotsAddResponse)(nil),    // 0: main.SpotsAddResponse
	(*SpotsAddData)(nil),        // 1: main.SpotsAddData
	(*SpotsUpdateResponse)(nil), // 2: main.SpotsUpdateResponse
	(*SpotsUpdateData)(nil),     // 3: main.SpotsUpdateData
	(*ResponseCoordinates)(nil), // 4: main.ResponseCoordinates
	(*SpotsGetResponse)(nil),    // 5: main.SpotsGetResponse
	(*SpotsGetData)(nil),        // 6: main.SpotsGetData
	(*SpotsGetAllResponse)(nil), // 7: main.SpotsGetAllResponse
}
var file_spots_proto_spots_response_proto_depIdxs = []int32{
	1, // 0: main.SpotsAddResponse.data:type_name -> main.SpotsAddData
	3, // 1: main.SpotsUpdateResponse.data:type_name -> main.SpotsUpdateData
	4, // 2: main.SpotsUpdateData.coordinates:type_name -> main.ResponseCoordinates
	6, // 3: main.SpotsGetResponse.data:type_name -> main.SpotsGetData
	4, // 4: main.SpotsGetData.coordinates:type_name -> main.ResponseCoordinates
	6, // 5: main.SpotsGetAllResponse.data:type_name -> main.SpotsGetData
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_spots_proto_spots_response_proto_init() }
func file_spots_proto_spots_response_proto_init() {
	if File_spots_proto_spots_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spots_proto_spots_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpotsAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spots_proto_spots_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpotsAddData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spots_proto_spots_response_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpotsUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spots_proto_spots_response_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpotsUpdateData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spots_proto_spots_response_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCoordinates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spots_proto_spots_response_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpotsGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spots_proto_spots_response_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpotsGetData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spots_proto_spots_response_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpotsGetAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spots_proto_spots_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spots_proto_spots_response_proto_goTypes,
		DependencyIndexes: file_spots_proto_spots_response_proto_depIdxs,
		MessageInfos:      file_spots_proto_spots_response_proto_msgTypes,
	}.Build()
	File_spots_proto_spots_response_proto = out.File
	file_spots_proto_spots_response_proto_rawDesc = nil
	file_spots_proto_spots_response_proto_goTypes = nil
	file_spots_proto_spots_response_proto_depIdxs = nil
}
