// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/spots_response.proto

package dto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SpotsAddResponse struct {
	Status               string        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *SpotsAddData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SpotsAddResponse) Reset()         { *m = SpotsAddResponse{} }
func (m *SpotsAddResponse) String() string { return proto.CompactTextString(m) }
func (*SpotsAddResponse) ProtoMessage()    {}
func (*SpotsAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2848f6407dc9789d, []int{0}
}

func (m *SpotsAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotsAddResponse.Unmarshal(m, b)
}
func (m *SpotsAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotsAddResponse.Marshal(b, m, deterministic)
}
func (m *SpotsAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotsAddResponse.Merge(m, src)
}
func (m *SpotsAddResponse) XXX_Size() int {
	return xxx_messageInfo_SpotsAddResponse.Size(m)
}
func (m *SpotsAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotsAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SpotsAddResponse proto.InternalMessageInfo

func (m *SpotsAddResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SpotsAddResponse) GetData() *SpotsAddData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SpotsAddData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpotsAddData) Reset()         { *m = SpotsAddData{} }
func (m *SpotsAddData) String() string { return proto.CompactTextString(m) }
func (*SpotsAddData) ProtoMessage()    {}
func (*SpotsAddData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2848f6407dc9789d, []int{1}
}

func (m *SpotsAddData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotsAddData.Unmarshal(m, b)
}
func (m *SpotsAddData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotsAddData.Marshal(b, m, deterministic)
}
func (m *SpotsAddData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotsAddData.Merge(m, src)
}
func (m *SpotsAddData) XXX_Size() int {
	return xxx_messageInfo_SpotsAddData.Size(m)
}
func (m *SpotsAddData) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotsAddData.DiscardUnknown(m)
}

var xxx_messageInfo_SpotsAddData proto.InternalMessageInfo

func (m *SpotsAddData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SpotsUpdateResponse struct {
	Status               string           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *SpotsUpdateData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SpotsUpdateResponse) Reset()         { *m = SpotsUpdateResponse{} }
func (m *SpotsUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*SpotsUpdateResponse) ProtoMessage()    {}
func (*SpotsUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2848f6407dc9789d, []int{2}
}

func (m *SpotsUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotsUpdateResponse.Unmarshal(m, b)
}
func (m *SpotsUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotsUpdateResponse.Marshal(b, m, deterministic)
}
func (m *SpotsUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotsUpdateResponse.Merge(m, src)
}
func (m *SpotsUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_SpotsUpdateResponse.Size(m)
}
func (m *SpotsUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotsUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SpotsUpdateResponse proto.InternalMessageInfo

func (m *SpotsUpdateResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SpotsUpdateResponse) GetData() *SpotsUpdateData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SpotsUpdateData struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Coordinates          *ResponseCoordinates `protobuf:"bytes,4,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Lighting             bool                 `protobuf:"varint,5,opt,name=lighting,proto3" json:"lighting,omitempty"`
	Friendly             bool                 `protobuf:"varint,6,opt,name=friendly,proto3" json:"friendly,omitempty"`
	Verified             bool                 `protobuf:"varint,7,opt,name=verified,proto3" json:"verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SpotsUpdateData) Reset()         { *m = SpotsUpdateData{} }
func (m *SpotsUpdateData) String() string { return proto.CompactTextString(m) }
func (*SpotsUpdateData) ProtoMessage()    {}
func (*SpotsUpdateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2848f6407dc9789d, []int{3}
}

func (m *SpotsUpdateData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotsUpdateData.Unmarshal(m, b)
}
func (m *SpotsUpdateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotsUpdateData.Marshal(b, m, deterministic)
}
func (m *SpotsUpdateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotsUpdateData.Merge(m, src)
}
func (m *SpotsUpdateData) XXX_Size() int {
	return xxx_messageInfo_SpotsUpdateData.Size(m)
}
func (m *SpotsUpdateData) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotsUpdateData.DiscardUnknown(m)
}

var xxx_messageInfo_SpotsUpdateData proto.InternalMessageInfo

func (m *SpotsUpdateData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SpotsUpdateData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SpotsUpdateData) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SpotsUpdateData) GetCoordinates() *ResponseCoordinates {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *SpotsUpdateData) GetLighting() bool {
	if m != nil {
		return m.Lighting
	}
	return false
}

func (m *SpotsUpdateData) GetFriendly() bool {
	if m != nil {
		return m.Friendly
	}
	return false
}

func (m *SpotsUpdateData) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

type ResponseCoordinates struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Long                 float64  `protobuf:"fixed64,2,opt,name=long,proto3" json:"long,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseCoordinates) Reset()         { *m = ResponseCoordinates{} }
func (m *ResponseCoordinates) String() string { return proto.CompactTextString(m) }
func (*ResponseCoordinates) ProtoMessage()    {}
func (*ResponseCoordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_2848f6407dc9789d, []int{4}
}

func (m *ResponseCoordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseCoordinates.Unmarshal(m, b)
}
func (m *ResponseCoordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseCoordinates.Marshal(b, m, deterministic)
}
func (m *ResponseCoordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseCoordinates.Merge(m, src)
}
func (m *ResponseCoordinates) XXX_Size() int {
	return xxx_messageInfo_ResponseCoordinates.Size(m)
}
func (m *ResponseCoordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseCoordinates.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseCoordinates proto.InternalMessageInfo

func (m *ResponseCoordinates) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *ResponseCoordinates) GetLong() float64 {
	if m != nil {
		return m.Long
	}
	return 0
}

type SpotsGetResponse struct {
	Status               string        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *SpotsGetData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SpotsGetResponse) Reset()         { *m = SpotsGetResponse{} }
func (m *SpotsGetResponse) String() string { return proto.CompactTextString(m) }
func (*SpotsGetResponse) ProtoMessage()    {}
func (*SpotsGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2848f6407dc9789d, []int{5}
}

func (m *SpotsGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotsGetResponse.Unmarshal(m, b)
}
func (m *SpotsGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotsGetResponse.Marshal(b, m, deterministic)
}
func (m *SpotsGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotsGetResponse.Merge(m, src)
}
func (m *SpotsGetResponse) XXX_Size() int {
	return xxx_messageInfo_SpotsGetResponse.Size(m)
}
func (m *SpotsGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotsGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SpotsGetResponse proto.InternalMessageInfo

func (m *SpotsGetResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SpotsGetResponse) GetData() *SpotsGetData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SpotsGetData struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Coordinates          *ResponseCoordinates `protobuf:"bytes,4,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Lighting             bool                 `protobuf:"varint,5,opt,name=lighting,proto3" json:"lighting,omitempty"`
	Friendly             bool                 `protobuf:"varint,6,opt,name=friendly,proto3" json:"friendly,omitempty"`
	Verified             bool                 `protobuf:"varint,7,opt,name=verified,proto3" json:"verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SpotsGetData) Reset()         { *m = SpotsGetData{} }
func (m *SpotsGetData) String() string { return proto.CompactTextString(m) }
func (*SpotsGetData) ProtoMessage()    {}
func (*SpotsGetData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2848f6407dc9789d, []int{6}
}

func (m *SpotsGetData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotsGetData.Unmarshal(m, b)
}
func (m *SpotsGetData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotsGetData.Marshal(b, m, deterministic)
}
func (m *SpotsGetData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotsGetData.Merge(m, src)
}
func (m *SpotsGetData) XXX_Size() int {
	return xxx_messageInfo_SpotsGetData.Size(m)
}
func (m *SpotsGetData) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotsGetData.DiscardUnknown(m)
}

var xxx_messageInfo_SpotsGetData proto.InternalMessageInfo

func (m *SpotsGetData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SpotsGetData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SpotsGetData) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SpotsGetData) GetCoordinates() *ResponseCoordinates {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *SpotsGetData) GetLighting() bool {
	if m != nil {
		return m.Lighting
	}
	return false
}

func (m *SpotsGetData) GetFriendly() bool {
	if m != nil {
		return m.Friendly
	}
	return false
}

func (m *SpotsGetData) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

type SpotsGetAllResponse struct {
	Status               string          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 []*SpotsGetData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SpotsGetAllResponse) Reset()         { *m = SpotsGetAllResponse{} }
func (m *SpotsGetAllResponse) String() string { return proto.CompactTextString(m) }
func (*SpotsGetAllResponse) ProtoMessage()    {}
func (*SpotsGetAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2848f6407dc9789d, []int{7}
}

func (m *SpotsGetAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotsGetAllResponse.Unmarshal(m, b)
}
func (m *SpotsGetAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotsGetAllResponse.Marshal(b, m, deterministic)
}
func (m *SpotsGetAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotsGetAllResponse.Merge(m, src)
}
func (m *SpotsGetAllResponse) XXX_Size() int {
	return xxx_messageInfo_SpotsGetAllResponse.Size(m)
}
func (m *SpotsGetAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotsGetAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SpotsGetAllResponse proto.InternalMessageInfo

func (m *SpotsGetAllResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SpotsGetAllResponse) GetData() []*SpotsGetData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*SpotsAddResponse)(nil), "main.SpotsAddResponse")
	proto.RegisterType((*SpotsAddData)(nil), "main.SpotsAddData")
	proto.RegisterType((*SpotsUpdateResponse)(nil), "main.SpotsUpdateResponse")
	proto.RegisterType((*SpotsUpdateData)(nil), "main.SpotsUpdateData")
	proto.RegisterType((*ResponseCoordinates)(nil), "main.ResponseCoordinates")
	proto.RegisterType((*SpotsGetResponse)(nil), "main.SpotsGetResponse")
	proto.RegisterType((*SpotsGetData)(nil), "main.SpotsGetData")
	proto.RegisterType((*SpotsGetAllResponse)(nil), "main.SpotsGetAllResponse")
}

func init() {
	proto.RegisterFile("proto/spots_response.proto", fileDescriptor_2848f6407dc9789d)
}

var fileDescriptor_2848f6407dc9789d = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x93, 0x4d, 0x4b, 0x33, 0x31,
	0x10, 0xc7, 0x49, 0xbb, 0x7d, 0x9b, 0x3e, 0x3c, 0x96, 0x14, 0x25, 0xf6, 0x20, 0x65, 0x0f, 0x52,
	0x2f, 0x5b, 0xd0, 0x63, 0x4f, 0x55, 0xa1, 0xf7, 0x48, 0x41, 0xbc, 0x48, 0x34, 0x69, 0x0d, 0x6c,
	0x93, 0x65, 0x33, 0x0a, 0x7e, 0x58, 0xc1, 0x8f, 0x22, 0x9b, 0xcd, 0xd6, 0xb5, 0x88, 0x22, 0xde,
	0xbc, 0xcd, 0x7f, 0x7e, 0xe9, 0xfc, 0xe7, 0xa5, 0x0b, 0xa3, 0x2c, 0xb7, 0x68, 0xa7, 0x2e, 0xb3,
	0xe8, 0x6e, 0x73, 0xe5, 0x32, 0x6b, 0x9c, 0x4a, 0x7c, 0x92, 0x46, 0x1b, 0xa1, 0x4d, 0xcc, 0x61,
	0x70, 0x55, 0xd0, 0xb9, 0x94, 0x3c, 0x70, 0x7a, 0x00, 0x6d, 0x87, 0x02, 0x1f, 0x1d, 0x23, 0x63,
	0x32, 0xe9, 0xf1, 0xa0, 0xe8, 0x31, 0x44, 0x52, 0xa0, 0x60, 0x8d, 0x31, 0x99, 0xf4, 0x4f, 0x69,
	0x52, 0x14, 0x48, 0xaa, 0x5f, 0x5f, 0x0a, 0x14, 0xdc, 0xf3, 0xf8, 0x08, 0xfe, 0xd5, 0xb3, 0xf4,
	0x3f, 0x34, 0xb4, 0x0c, 0xb5, 0x1a, 0x5a, 0xc6, 0xd7, 0x30, 0xf4, 0x7c, 0x99, 0x49, 0x81, 0xea,
	0x5b, 0xdb, 0x93, 0x0f, 0xb6, 0xfb, 0x35, 0xdb, 0xb2, 0x40, 0xcd, 0xf9, 0x95, 0xc0, 0xde, 0x0e,
	0xd9, 0x75, 0xa7, 0x14, 0x22, 0x23, 0x36, 0xca, 0x97, 0xeb, 0x71, 0x1f, 0x53, 0x06, 0x1d, 0x21,
	0x65, 0xae, 0x9c, 0x63, 0x4d, 0x9f, 0xae, 0x24, 0x9d, 0x41, 0xff, 0xde, 0xda, 0x5c, 0x6a, 0x23,
	0x50, 0x39, 0x16, 0xf9, 0x1e, 0x0e, 0xcb, 0x1e, 0xaa, 0xce, 0x2f, 0xde, 0x1f, 0xf0, 0xfa, 0x6b,
	0x3a, 0x82, 0x6e, 0xaa, 0xd7, 0x0f, 0xa8, 0xcd, 0x9a, 0xb5, 0xc6, 0x64, 0xd2, 0xe5, 0x5b, 0x5d,
	0xb0, 0x55, 0xae, 0x95, 0x91, 0xe9, 0x33, 0x6b, 0x97, 0xac, 0xd2, 0x05, 0x7b, 0x52, 0xb9, 0x5e,
	0x69, 0x25, 0x59, 0xa7, 0x64, 0x95, 0x8e, 0x67, 0x30, 0xfc, 0xc4, 0x97, 0x0e, 0xa0, 0x99, 0x0a,
	0xf4, 0x63, 0x12, 0x5e, 0x84, 0xc5, 0x9c, 0xa9, 0x35, 0x6b, 0x3f, 0x27, 0xe1, 0x3e, 0xde, 0x5e,
	0x7b, 0xa1, 0xf0, 0x17, 0xd7, 0x5e, 0x28, 0xac, 0xed, 0xfc, 0x85, 0x84, 0x73, 0x87, 0xf4, 0x5f,
	0x5b, 0xf8, 0x32, 0xfc, 0x5b, 0x17, 0x0a, 0xe7, 0x69, 0xfa, 0x83, 0xb5, 0x35, 0xbf, 0x5a, 0xdb,
	0x79, 0xe7, 0xa6, 0x95, 0x4c, 0x25, 0xda, 0xbb, 0xb6, 0xff, 0x1c, 0xcf, 0xde, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xa2, 0x7a, 0xba, 0x10, 0xac, 0x03, 0x00, 0x00,
}
