// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: places/proto/autocomplete_request.proto

package dto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on AutocompleteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *AutocompleteRequest) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetSearch()) < 1 {
		return AutocompleteRequestValidationError{
			field:  "Search",
			reason: "value length must be at least 1 runes",
		}
	}

	if _, ok := _AutocompleteRequest_Language_InLookup[m.GetLanguage()]; !ok {
		return AutocompleteRequestValidationError{
			field:  "Language",
			reason: "value must be in list [pl en]",
		}
	}

	return nil
}

// AutocompleteRequestValidationError is the validation error returned by
// AutocompleteRequest.Validate if the designated constraints aren't met.
type AutocompleteRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AutocompleteRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AutocompleteRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AutocompleteRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AutocompleteRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AutocompleteRequestValidationError) ErrorName() string {
	return "AutocompleteRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AutocompleteRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAutocompleteRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AutocompleteRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AutocompleteRequestValidationError{}

var _AutocompleteRequest_Language_InLookup = map[string]struct{}{
	"pl": {},
	"en": {},
}
