// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: places/proto/autocomplete_response.proto

package dto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on AutocompleteEntry with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *AutocompleteEntry) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetCoordinates()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AutocompleteEntryValidationError{
				field:  "Coordinates",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Name

	// no validation rules for Address

	return nil
}

// AutocompleteEntryValidationError is the validation error returned by
// AutocompleteEntry.Validate if the designated constraints aren't met.
type AutocompleteEntryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AutocompleteEntryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AutocompleteEntryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AutocompleteEntryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AutocompleteEntryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AutocompleteEntryValidationError) ErrorName() string {
	return "AutocompleteEntryValidationError"
}

// Error satisfies the builtin error interface
func (e AutocompleteEntryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAutocompleteEntry.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AutocompleteEntryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AutocompleteEntryValidationError{}

// Validate checks the field values on Coordinates with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *Coordinates) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Lat

	// no validation rules for Long

	return nil
}

// CoordinatesValidationError is the validation error returned by
// Coordinates.Validate if the designated constraints aren't met.
type CoordinatesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CoordinatesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CoordinatesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CoordinatesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CoordinatesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CoordinatesValidationError) ErrorName() string { return "CoordinatesValidationError" }

// Error satisfies the builtin error interface
func (e CoordinatesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCoordinates.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CoordinatesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CoordinatesValidationError{}

// Validate checks the field values on AutocompleteResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *AutocompleteResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Status

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AutocompleteResponseValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// AutocompleteResponseValidationError is the validation error returned by
// AutocompleteResponse.Validate if the designated constraints aren't met.
type AutocompleteResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AutocompleteResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AutocompleteResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AutocompleteResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AutocompleteResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AutocompleteResponseValidationError) ErrorName() string {
	return "AutocompleteResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AutocompleteResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAutocompleteResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AutocompleteResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AutocompleteResponseValidationError{}
