// Code generated by MockGen. DO NOT EDIT.
// Source: sk8.town/backside/spots/domain (interfaces: FiltersRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	errs "sk8.town/backside/errs"
	domain "sk8.town/backside/spots/domain"
)

// MockFiltersRepository is a mock of FiltersRepository interface.
type MockFiltersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFiltersRepositoryMockRecorder
}

// MockFiltersRepositoryMockRecorder is the mock recorder for MockFiltersRepository.
type MockFiltersRepositoryMockRecorder struct {
	mock *MockFiltersRepository
}

// NewMockFiltersRepository creates a new mock instance.
func NewMockFiltersRepository(ctrl *gomock.Controller) *MockFiltersRepository {
	mock := &MockFiltersRepository{ctrl: ctrl}
	mock.recorder = &MockFiltersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFiltersRepository) EXPECT() *MockFiltersRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockFiltersRepository) GetAll() ([]*domain.Filter, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*domain.Filter)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockFiltersRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockFiltersRepository)(nil).GetAll))
}
