// Code generated by MockGen. DO NOT EDIT.
// Source: sk8.town/backside/spots (interfaces: SpotsService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	errs "sk8.town/backside/errs"
	dto "sk8.town/backside/spots/dto"
)

// MockSpotsService is a mock of SpotsService interface.
type MockSpotsService struct {
	ctrl     *gomock.Controller
	recorder *MockSpotsServiceMockRecorder
}

// MockSpotsServiceMockRecorder is the mock recorder for MockSpotsService.
type MockSpotsServiceMockRecorder struct {
	mock *MockSpotsService
}

// NewMockSpotsService creates a new mock instance.
func NewMockSpotsService(ctrl *gomock.Controller) *MockSpotsService {
	mock := &MockSpotsService{ctrl: ctrl}
	mock.recorder = &MockSpotsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotsService) EXPECT() *MockSpotsServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockSpotsService) Add(arg0 *dto.SpotsAddRequest) (*dto.SpotsAddData, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0)
	ret0, _ := ret[0].(*dto.SpotsAddData)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockSpotsServiceMockRecorder) Add(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockSpotsService)(nil).Add), arg0)
}

// Delete mocks base method.
func (m *MockSpotsService) Delete(arg0 int) *errs.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(*errs.AppError)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSpotsServiceMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSpotsService)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockSpotsService) Get(arg0 int) (*dto.SpotsGetData, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*dto.SpotsGetData)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSpotsServiceMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSpotsService)(nil).Get), arg0)
}

// GetAll mocks base method.
func (m *MockSpotsService) GetAll() ([]*dto.SpotsGetData, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*dto.SpotsGetData)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockSpotsServiceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSpotsService)(nil).GetAll))
}

// Update mocks base method.
func (m *MockSpotsService) Update(arg0 int, arg1 *dto.SpotsUpdateRequest) (*dto.SpotsUpdateData, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*dto.SpotsUpdateData)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSpotsServiceMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSpotsService)(nil).Update), arg0, arg1)
}
