// Code generated by MockGen. DO NOT EDIT.
// Source: sk8.town/backside/spots (interfaces: SpotService)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	errs "sk8.town/backside/errs"
	dto "sk8.town/backside/spots/dto"
)

// MockSpotService is a mock of SpotService interface
type MockSpotService struct {
	ctrl     *gomock.Controller
	recorder *MockSpotServiceMockRecorder
}

// MockSpotServiceMockRecorder is the mock recorder for MockSpotService
type MockSpotServiceMockRecorder struct {
	mock *MockSpotService
}

// NewMockSpotService creates a new mock instance
func NewMockSpotService(ctrl *gomock.Controller) *MockSpotService {
	mock := &MockSpotService{ctrl: ctrl}
	mock.recorder = &MockSpotServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSpotService) EXPECT() *MockSpotServiceMockRecorder {
	return m.recorder
}

// Add mocks base method
func (m *MockSpotService) Add(arg0 *dto.SpotsAddRequest) (*dto.SpotsAddData, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0)
	ret0, _ := ret[0].(*dto.SpotsAddData)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// Add indicates an expected call of Add
func (mr *MockSpotServiceMockRecorder) Add(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockSpotService)(nil).Add), arg0)
}

// Delete mocks base method
func (m *MockSpotService) Delete(arg0 int) *errs.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(*errs.AppError)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockSpotServiceMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSpotService)(nil).Delete), arg0)
}

// Get mocks base method
func (m *MockSpotService) Get(arg0 int) (*dto.SpotsGetData, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*dto.SpotsGetData)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockSpotServiceMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSpotService)(nil).Get), arg0)
}

// GetAll mocks base method
func (m *MockSpotService) GetAll() ([]*dto.SpotsGetData, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*dto.SpotsGetData)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockSpotServiceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSpotService)(nil).GetAll))
}

// Update mocks base method
func (m *MockSpotService) Update(arg0 int, arg1 *dto.SpotsUpdateRequest) (*dto.SpotsUpdateData, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*dto.SpotsUpdateData)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *MockSpotServiceMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSpotService)(nil).Update), arg0, arg1)
}
