// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: auth/proto/login_request_body.proto

package dto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on LoginRequestBody with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *LoginRequestBody) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for IdToken

	return nil
}

// LoginRequestBodyValidationError is the validation error returned by
// LoginRequestBody.Validate if the designated constraints aren't met.
type LoginRequestBodyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginRequestBodyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginRequestBodyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginRequestBodyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginRequestBodyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginRequestBodyValidationError) ErrorName() string { return "LoginRequestBodyValidationError" }

// Error satisfies the builtin error interface
func (e LoginRequestBodyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginRequestBody.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginRequestBodyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginRequestBodyValidationError{}
