// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/proto/login_response_body.proto

package dto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginResponseBody struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponseBody) Reset()         { *m = LoginResponseBody{} }
func (m *LoginResponseBody) String() string { return proto.CompactTextString(m) }
func (*LoginResponseBody) ProtoMessage()    {}
func (*LoginResponseBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c0dd7cc5171a51, []int{0}
}

func (m *LoginResponseBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponseBody.Unmarshal(m, b)
}
func (m *LoginResponseBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponseBody.Marshal(b, m, deterministic)
}
func (m *LoginResponseBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponseBody.Merge(m, src)
}
func (m *LoginResponseBody) XXX_Size() int {
	return xxx_messageInfo_LoginResponseBody.Size(m)
}
func (m *LoginResponseBody) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponseBody.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponseBody proto.InternalMessageInfo

func (m *LoginResponseBody) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginResponseBody)(nil), "main.LoginResponseBody")
}

func init() {
	proto.RegisterFile("auth/proto/login_response_body.proto", fileDescriptor_01c0dd7cc5171a51)
}

var fileDescriptor_01c0dd7cc5171a51 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x49, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0xc9, 0x4f, 0xcf, 0xcc, 0x8b, 0x2f, 0x4a, 0x2d,
	0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x8d, 0x4f, 0xca, 0x4f, 0xa9, 0xd4, 0x03, 0xcb, 0x08, 0xb1, 0xe4,
	0x26, 0x66, 0xe6, 0x29, 0x69, 0x72, 0x09, 0xfa, 0x80, 0x94, 0x04, 0x41, 0x55, 0x38, 0xe5, 0xa7,
	0x54, 0x0a, 0x89, 0x70, 0xb1, 0x96, 0xe4, 0x67, 0xa7, 0xe6, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0x41, 0x38, 0x4e, 0xec, 0x51, 0xac, 0x7a, 0xfa, 0x29, 0x25, 0xf9, 0x49, 0x6c, 0x60, 0x03,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x19, 0x8c, 0x8c, 0x68, 0x00, 0x00, 0x00,
}
