// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: auth/proto/login_response_body.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginResponseBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   *LoginResponseData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *LoginResponseBody) Reset() {
	*x = LoginResponseBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_proto_login_response_body_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponseBody) ProtoMessage() {}

func (x *LoginResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_login_response_body_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponseBody.ProtoReflect.Descriptor instead.
func (*LoginResponseBody) Descriptor() ([]byte, []int) {
	return file_auth_proto_login_response_body_proto_rawDescGZIP(), []int{0}
}

func (x *LoginResponseBody) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoginResponseBody) GetData() *LoginResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoginResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LoginResponseData) Reset() {
	*x = LoginResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_proto_login_response_body_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponseData) ProtoMessage() {}

func (x *LoginResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_login_response_body_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponseData.ProtoReflect.Descriptor instead.
func (*LoginResponseData) Descriptor() ([]byte, []int) {
	return file_auth_proto_login_response_body_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponseData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_auth_proto_login_response_body_proto protoreflect.FileDescriptor

var file_auth_proto_login_response_body_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x62, 0x6f, 0x64, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x58, 0x0a, 0x11,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x29, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x64, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_auth_proto_login_response_body_proto_rawDescOnce sync.Once
	file_auth_proto_login_response_body_proto_rawDescData = file_auth_proto_login_response_body_proto_rawDesc
)

func file_auth_proto_login_response_body_proto_rawDescGZIP() []byte {
	file_auth_proto_login_response_body_proto_rawDescOnce.Do(func() {
		file_auth_proto_login_response_body_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_proto_login_response_body_proto_rawDescData)
	})
	return file_auth_proto_login_response_body_proto_rawDescData
}

var file_auth_proto_login_response_body_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_proto_login_response_body_proto_goTypes = []interface{}{
	(*LoginResponseBody)(nil), // 0: main.LoginResponseBody
	(*LoginResponseData)(nil), // 1: main.LoginResponseData
}
var file_auth_proto_login_response_body_proto_depIdxs = []int32{
	1, // 0: main.LoginResponseBody.data:type_name -> main.LoginResponseData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auth_proto_login_response_body_proto_init() }
func file_auth_proto_login_response_body_proto_init() {
	if File_auth_proto_login_response_body_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auth_proto_login_response_body_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponseBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_proto_login_response_body_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_proto_login_response_body_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_proto_login_response_body_proto_goTypes,
		DependencyIndexes: file_auth_proto_login_response_body_proto_depIdxs,
		MessageInfos:      file_auth_proto_login_response_body_proto_msgTypes,
	}.Build()
	File_auth_proto_login_response_body_proto = out.File
	file_auth_proto_login_response_body_proto_rawDesc = nil
	file_auth_proto_login_response_body_proto_goTypes = nil
	file_auth_proto_login_response_body_proto_depIdxs = nil
}
