# Production
version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=$SK8_DB_USER
      - POSTGRES_PASSWORD=$SK8_DB_PASSWORD
      - POSTGRES_DB=$SK8_DB_NAME

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: $SK8_AUTH_DB_NAME
      MONGO_INITDB_ROOT_USERNAME: $SK8_AUTH_DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $SK8_AUTH_DB_PASSWORD

  backside:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - SK8_PORT=8080

      - SK8_DB_HOST=$SK8_DB_HOST
      - SK8_DB_PORT=$SK8_DB_PORT
      - SK8_DB_USER=$SK8_DB_USER
      - SK8_DB_PASSWORD=$SK8_DB_PASSWORD
      - SK8_DB_NAME=$SK8_DB_NAME

      - SK8_PLACES_TOMTOM_API_KEY=$SK8_PLACES_TOMTOM_API_KEY
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongodb
