# Development

version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=$SK8_DB_USER
      - POSTGRES_PASSWORD=$SK8_DB_PASSWORD
      - POSTGRES_DB=$SK8_DB_NAME
  backside:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - SK8_ADDRESS=$SK8_ADDRESS
      - SK8_PORT=$SK8_PORT

      - SK8_DB_HOST=$SK8_DB_HOST
      - SK8_DB_PORT=$SK8_DB_PORT
      - SK8_DB_USER=$SK8_DB_USER
      - SK8_DB_PASSWORD=$SK8_DB_PASSWORD
      - SK8_DB_NAME=$SK8_DB_NAME
      - SK8_DB_DROP_ALL_TABLES=${SK8_DB_DROP_ALL_TABLES:-false}

      - SK8_PLACES_TOMTOM_API_KEY=$SK8_PLACES_TOMTOM_API_KEY
    ports:
      - "$SK8_PORT:$SK8_PORT"
    volumes:
      - ./:/home/app
