# Development

FROM golang:alpine3.14

WORKDIR /home/app

RUN go get github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon \
    --build="go build -o backside" \
    --command="./backside" \
    --exclude=".git"
