service: sk8-backside

frameworkVersion: '2'

provider:
  name: aws
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  hello:
    runtime: go1.x
    handler: bin/hello
    events:
      - http: GET /hello
  world:
    runtime: go1.x
    handler: bin/world
    events:
      - http: GET /world
