name: frontside-deployment
on:
  push:
    branches:
      - testflight
    paths:
      - ".github/workflows/**"
      - "frontside/**" # run only when frontside is affected
jobs:
  deploy-ios:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./frontside
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1

      - name: Build
        run: flutter build ipa

      # - name: 'Upload to TestFlight'
      #   uses: apple-actions/upload-testflight-build@v1
      #   with: 
      #     app-path: 'build/application.ipa' 
      #     issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
      #     api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
      #     api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

  # deploy-web:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./frontside
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v1

  #     - name: Build
  #       run: flutter build web

  #     - name: Upload to S3
  #       uses: jakejarvis/s3-sync-action@master
  #       with:
  #         args: --follow-symlinks --delete
  #       env:
  #         AWS_S3_BUCKET: web.sk8.town
  #         AWS_ACCESS_KEY_ID: ${{ secrets.CI_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_SECRET_ACCESS_KEY }}
  #         AWS_REGION: "eu-west-1"
  #         SOURCE_DIR: "frontside/build/web"

  #     - name: Invalidate CloudFront
  #       uses: chetan/invalidate-cloudfront-action@master
  #       env:
  #         DISTRIBUTION: ${{ secrets.DISTRIBUTION_WEB_SK8_TOWN }}
  #         PATHS: '/*'
  #         AWS_REGION: 'eu-west-1'
  #         AWS_ACCESS_KEY_ID: ${{ secrets.CI_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_SECRET_ACCESS_KEY }}
