name: frontside
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - ".github/workflows/**"
      - "frontside/**" # run only when frontside is affected
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontside
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup flutter environment
        uses: subosito/flutter-action@v1

      - name: Analyze
        run: flutter analyze
