name: frontside-web-deployment
on:
  push:
    branches:
      - deploy-frontside-web
    paths:
      - ".github/workflows/**"
      - "frontside/**" # run only when frontside is affected
jobs:
  deploy-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontside
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup flutter environment
        uses: subosito/flutter-action@v1

      - name: Build
        run: flutter build web --release

      - name: Deploy
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: web.sk8.town
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1"
          SOURCE_DIR: "frontside/build/web"
