name: frontside
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Hello world
      - name: Hello world
        run: |
          exit 1
