name: pr-checks
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            backside:
              - 'backside/**'
            frontside:
              - 'frontside/**'

      - name: Checkout
        if: steps.changes.outputs.frontside == 'true'
        uses: actions/checkout@v2

      - name: Setup flutter environment
        if: steps.changes.outputs.frontside == 'true'
        uses: subosito/flutter-action@v1

      - name: Analyze
        if: steps.changes.outputs.frontside == 'true'
        working-directory: ./frontside
        run: flutter analyze
