name: pr-checks
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            backside:
              - 'backside/**'
            frontside:
              - 'frontside/**'

      - name: Checkout
        if: ${{ contains(steps.changes.outputs.*, 'true') }}
        uses: actions/checkout@v2

      # Frontside
      - name: Setup flutter environment
        if: steps.changes.outputs.frontside == 'true'
        uses: subosito/flutter-action@v1

      - name: Analyze
        if: steps.changes.outputs.frontside == 'true'
        working-directory: ./frontside
        run: flutter analyze

      - name: Format
        if: steps.changes.outputs.frontside == 'true'
        working-directory: ./frontside
        run: flutter format --set-exit-if-changed .

      # Backside
      - name: Lint (golangci-lint)
        if: steps.changes.outputs.backside == 'true'
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: backside/places-microservice # subject to change
